<?php

namespace Database\Seeders;

use App\Models\Merchant;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MerchantTableSeeder extends Seeder
{
    public function run()
    {
        $merchant = [
            [
                'id'               => 1,
                'name'             => 'Home Cleaning Enterprises',
                'description'      => 'Home cleaning, Toliet Cleaning, Bedroom Cleaning, Living Room Cleaning, Carpark Cleaning.',
                'contact_number'   => '+604343541638',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => '34, Jalan Sini 56, Taman University',
                'state_id'         => 79,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
            [
                'id'               => 2,
                'name'             => 'MamaLove Cleaning Sdn Bhd',
                'description'      => 'We are professional cleaning company, we have 10++ home cleaning services.',
                'contact_number'   => '+607-2882207',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => '50-01, Jalan Setia Tropika 1/29, Setia Tropika',
                'state_id'         => 78,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
            [
                'id'               => 3,
                'name'             => 'MaidnClean Johor Bahru',
                'description'      => 'Home cleaning, Bedroom Cleaning, Living Room Cleaning',
                'contact_number'   => '+6018-399 0366',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => '31 jalan seri orkid 17 taman seri orkid skudai',
                'state_id'         => 79,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
            [
                'id'               => 4,
                'name'             => 'Johor Plumbing Services',
                'description'      => 'We work with architects and designers to produce quality, functional plumbing system . Call us today and bring our project experience skills  to your next project.',
                'contact_number'   => '+6016-477 0739',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => 'Blok 4, 1-2, Jalan Camar 12, Taman Perling',
                'state_id'         => 78,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
            [
                'id'               => 5,
                'name'             => 'Dr Plumber (Tukang Paip) JB - Johor Bahru',
                'description'      => 'Dr Plumber JB berkhidmat 24 Jam, 7 Hari seminggu  memberikan khidmat terbaik dan professional kepada anda. Dijamin anda akan berpuas hati dengan kualiti kerja , harga dan khidmat nasihat yang di berikan . ',
                'contact_number'   => '+6013-781 7454',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => 'No 4, 9, Jalan Laman Indah, Taman Laman Indah',
                'state_id'         => 79,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
            [
                'id'               => 6,
                'name'             => 'Ah Wing Plumbing Repair Service',
                'description'      => 'Plumbing Repair',
                'contact_number'   => '+6016-711 3824',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => 'No 66, Jalan Seri Orkid 34, Taman Seri Orkid',
                'state_id'         => 79,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
            [
                'id'               => 7,
                'name'             => 'Aircon Services Company',
                'description'      => 'Install Aircon, Washing Aircon, Service Aircon',
                'contact_number'   => '+60245ddd4',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => '888, Jalan Impian 34, Taman Impian Emas',
                'state_id'         => 79,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
            [
                'id'               => 8,
                'name'             => 'Aircon Service JB',
                'description'      => 'We offer a variety of fairly priced aircon service options that cater to both residential and commercial clients. In order to ensure optimal aircon performance for your home or business, you may also consider our annual Contract Servicing package.',
                'contact_number'   => '+6018-328 1173',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => '18, Jalan Perkasa 3, Taman Ungku Tun Aminah',
                'state_id'         => 79,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
            [
                'id'               => 9,
                'name'             => 'Kaili Aircon & Electrical Sdn Bhd',
                'description'      => 'Our company was started in year 1999 as a sub-contractor providing air-conditioning installation, trouble shooting, repair and maintenance services for various authorized dealers. And we also deal in reused air-conditioners locally.',
                'contact_number'   => '+607-512 3112',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => '26, Jalan Nb2 1/4, Taman Nusa Bestari 2',
                'state_id'         => 79,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
            [
                'id'               => 10,
                'name'             => 'WBC ELECTRICAL SERVICE',
                'description'      => 'Electrical Services',
                'contact_number'   => '+6011-1115 1228',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => 'Taman Bukit Tropika',
                'state_id'         => 163,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
            [
                'id'               => 11,
                'name'             => 'Tan Electrical Service',
                'description'      => 'Electrical Services, Wiring Service',
                'contact_number'   => '+607-556 3876',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => '28&30, Jalan Perwira 1, Taman Ungku Tun Aminah',
                'state_id'         => 79,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
            [
                'id'               => 12,
                'name'             => 'TL Electrical & Engineering JB',
                'description'      => 'Electrical Installation Service in tampoi Open 24 hours',
                'contact_number'   => '+6018-961 7200',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => 'No 7, Jalan Bukit Kempas 4, Taman Bukit Kempas',
                'state_id'         => 78,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
            [
                'id'               => 13,
                'name'             => 'ELECTRICAL WIRING AND AIRCOND SERVICE',
                'description'      => 'Electrical and Wring Service',
                'contact_number'   => '+6011-1996 5578',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => '19, Jalan Pulai Perdana 11, Taman Sri Pulai Perdana',
                'state_id'         => 77,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
            [
                'id'               => 14,
                'name'             => 'JB Automobile Wiring',
                'description'      => 'Electrical Installation Service in tampoi Open 24 hours',
                'contact_number'   => '+6019-711 2143',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => 'No. 23, Jalan Sri Purnama 2/1, Kangkar Tebrau',
                'state_id'         => 77,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
            [
                'id'               => 15,
                'name'             => 'ACC Tech. | Electrical Wiring | Fiber Optic Johor Bahru',
                'description'      => 'ACC Technology Solution Sdn Bhd is a company specializing in electrical wiring in Johor Bahru. With a team of electrician that has more than 15 years of field experience, we aim of helping our client solve all kind of electrical wiring issue.',
                'contact_number'   => '+6019-769 6828',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => '32, Jalan Ros Merah 2/3, Johor Jaya',
                'state_id'         => 77,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
            [
                'id'               => 16,
                'name'             => 'XPERT GADGET JB (Skudai) - Mobile Phone Repair Specialist',
                'description'      => 'Mobile Phone Repair Shop in Taman Universiti Open today until 8:00 PM.',
                'contact_number'   => '+6019-916 9160',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => '10, Jalan Pendidikan 8, Taman Universiti',
                'state_id'         => 79,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
            [
                'id'               => 17,
                'name'             => 'Pro Mobile Fix JB',
                'description'      => 'Repair Iphone , Android dan Tablet Skudai , Kangkar Pulai, Johor.',
                'contact_number'   => '+6011-2835 2675',
                'status'           => 'approved',
                'delivery_fee'      => "above 10KM delivery will be change RM10",
                'address'          => '79, Jalan Pulai Perdana 11 Taman Sri Pulai Perdana Kangkar',
                'state_id'         => 77,
                'ssm_number'       => Str::random(8).'-T',
                'created_by_id'    => 1,
            ],
        ];

        Merchant::insert($merchant);
    }
}
